# Use same PostgreSQL as renren-fast (e.g. AWS RDS) when running with profile=dev
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://***REMOVED***:5432/ecommerce_pms
    username: postgres
    password: ***REMOVED***
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true   # print SQL to console
    properties:
      hibernate:
        format_sql: true
